[build]
  base = "Admin-ui"
  command = "npm run build"
  publish = "dist"   # NOT Admin-ui/dist

# Proxy API requests to Render
[[redirects]]
  from = "/api/*"
  to = "https://hrmadmin-nodeproxxy.onrender.com/:splat"
  status = 200
  force = true

# React SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
