export const TOKEN_KEY = 'auth_token'
export const APIRoutes = {
  // BASEURL:"https://hrmadmin-nodeproxxy.onrender.com/",
  BASEURL: import.meta.env.VITE_API_URL,
  PROXY: '/api/proxy',
  UPLOADPROXY: '/api/upload',
  CHUNKS: 'getHRMChunks',
  SEARCH: 'search',
  SEARCHBYCODE: 'searchbycode',
  LOGIN: 'login',
  AGENTBYID: 'Agentbyid',
  AGENTBYCODE: 'AgentByCode',
  GETCOMMISSIONDATA: 'getCommissionData',
  GETMASTERS: 'GetMasters',
  PROCESSCOMMISSION: 'processCommission',
  HOLDCOMMISSION: 'holdCommission',
  ADJUSTCOMMISSION: 'adjustCommission',
  APPROVECOMMISSION: 'approveCommission',
  CONFIG_COMMISSION: 'configcommission',
  UPDATE_CONDITION_CONFIG: 'updateConditionConfig',
  CONFIG_LIST: 'configList',
  UPDATE_CRON: 'updateCron',
  UPDATE_STATUS: 'updateStatus',
  COMMISSION_SEARCH_FIELDS: 'searchFieldsConfig',
  EDIT_AGENT: 'editAgentDetails',
  EXECUTIVE_HISTORY_LIST: 'executiveHistoryList',
  UPDATE_COMMISSION_CONFIG: 'editCommission',
  DOWNLOAD_RECORD: 'downloadRecord',
  GEO_HIERARCHY: 'GeoHierarchy',
  GEO_HIERARCHY_TABLE: 'GeoHierarchyTable',
  HMS_DASHBOARD: 'hmsDashboard',
  GET_GRAPH_DATA: 'getGraphData',
  HMS_OVERVIEW_STATS: 'getChannelStats',
  UPLOAD_FILE_LIST: 'uploadFileList',
  DOWNLOAD_REPORT: 'downloadReport',
  HMS_FILE: 'file',
  GET_ROLES: 'rolesList',
  GET_WEIGHTAGES: 'getWeightages',
  DELETE_ROLES: "deleteRole",
  FETCH_MENU: "fetchMenu",
  GET_INCENTIVE_KPI_LIBRARY: 'getIncentiveKpiLibrary',
  GET_INCENTIVE_KPI_BY_ID: 'getIncentiveKpiById',
  CREATE_INCENTIVE_KPI: 'createIncentiveKpi',
  UPDATE_INCENTIVE_KPI: 'updateIncentiveKpi',
  DELETE_INCENTIVE_KPI: 'deleteIncentiveKpi',
  GET_INCENTIVE_FILTERS: 'getIncentiveFilters',
  GET_INCENTIVE_PROGRAM_BY_ID: 'getIncentiveProgramById',
  CREATE_INCENTIVE_PROGRAM: 'createIncentiveProgram',
  UPDATE_INCENTIVE_PROGRAM: 'updateIncentiveProgram',
  GET_INCENTIVE_PROGRAM_PRODUCT_WEIGHTAGE: 'getIncentiveProgramProductWeightage',
  SAVE_INCENTIVE_PROGRAM_PRODUCT_WEIGHTAGE: 'saveIncentiveProgramProductWeightage',
  CREATE_WEIGHTAGE_MASTER: 'createWeightageMaster',
  CREATE_WEIGHTAGE_DETAILS: 'createWeightageDetails',
  DELETE_WEIGHTAGE_DETAILS: 'deleteWeightageDetails',
  SAVE_WEIGHTAGE_DIMENSION: 'saveWeightageDimension',
  ROLE_USER_LIST: "userList",
  GRANT_MENU_ACCESS: "grantMenu",
  REVOKE_MENU_ACCESS: "revokeMenu",
  SUB_CHANNEL_LIST: "getSubChannel",
  ALLOW_UI_ACCESS: "allowUiAccess",
  FETCH_INBOX_DATA: "fetchInboxData",
  UPDATE_SR_DECISION: "updateSrDecision",
  GET_USER_DETAILS: "getUserDetails",
  CREATE_USER: "createUser",
  UPDATE_USER: "updateUser",
  UPDATE_PASSWORD: "updatePassword",
  ACTIVATE_DEACTIVATE_USER: "activateDeactivateUser",
  LOCK_UNLOCK_USER: "lockUnlockUser",
  ORG_CONFIG: "orgConfiguration",
  ORG_CONFIG_UPDATE: "orgConfigUpdate",
  FETCH_ALL_AGENTS: 'fetchAllBranches',
  SAVE_BRANCH_LINK: 'saveBranchLinkedAgent',
  FETCH_BRANCHES_BY_AGENT: 'fetchBranchByAgent',
  SAVE_BRANCH_LINKED_USER: 'saveBranchLinkedUser',
  FETCH_BRANCH_BY_USER: 'fetchBranchByUser',
  CREATE_INDIVIDUAL_AGENT: 'CreateIndividualAgent',
  SAVE_PRODUCT: 'SaveProduct',
  GET_PRODUCTS: 'GetProducts',
  INCENTIVE_UPSERT_PROGRAM: 'upsertProgram',
  INCENTIVE_GET_KPIS_LIST: 'getKpisList',
  INCENTIVE_GET_SELECTED_PROGRAM_KPIS: 'getSelectedProgramKpis',
  INCENTIVE_UPSERT_PROGRAM_WEIGHTAGES: 'upsertProgramWeightages',
  INCENTIVE_GET_PROGRAMS_LIST: 'getProgramsList',
  INCENTIVE_GET_PAST_QUALIFICATIONS: 'getPastQualifications',
  GET_FILTERS_CASCADE: 'getFiltersCascade',
  UPSERT_PROGRAM_FILTERS: 'upsertProgramFilters',
  INCENTIVE_GET_KPI_OBJECTS: 'GetKpiObjects',
  INCENTIVE_GET_KPI_FIELDS: 'GetKpiFields',
  INCENTIVE_GET_TABLE_SCHEMA: 'GetTableSchema',
  INCENTIVE_UPSERT_KPI: 'UpsertKpi',
}

export const LoginConstants = {
  INVALID_CREDENTIALS: 1001,
  ACCOUNT_LOCKED: 1002,
  NO_ACTIVE_PRIMARY_ROLE: 1003,
}

export const CommonConstants = {
  SUCCESS: 1101,
}

export const AgentConstants = {
  AGENT_NOTFOUND: 1201,
}
