const APIRoutes = {
  LOGIN: "/api/Auth/Login",
  AGENTSEARCH: "/api/Agent/Search",
  AGENTBYCODE: "/api/Agent/AgentByCode",
  AGENTBYID: "/api/Agent/AgentByid",
  GETMASTERS: "/api/AppMasters/get",
  GETWEIGHTAGES: "/api/incentive/GetWeightages",
  GETCOMMISSION: "/api/CommissionMgmt/Dashboard",
  PROCESSCOMMISSION: "/api/CommissionMgmt/ProcessCommissions",
  HOLDCOMMISSION: "/api/CommissionMgmt/HoldCommission",
  ADJUSTCOMMISSION: "/api/CommissionMgmt/AdjustCommission",
  APPROVECOMMISSION: "/api/CommissionMgmt/ApproveCommission",
  CONFIGCOMMISSION: "/api/CommissionConfig/CreateCommission",
  UPDATECONDITIONCONFIG: "/api/CommissionConfig/UpdateCommissionFormula",
  CONFIGLIST: "/api/CommissionConfig/CommissionJobConfigPaginatedList",
  UPDATECRON: "/api/CommissionConfig/UpdateCronSetting",
  UPDATESTATUS: "/api/CommissionConfig/EnableDisableJob",
  COMMISSIONSEARCHFIELDS: "/api/MetaData/Fetch",
  EXECUTIVEHISTORYLIST: "/api/CommissionConfig/JobExecutionHistory",
  EDITAGENT: "/api/Agent/UpdateAgent",
  UPDATECOMMISSIONBYID: "/api/CommissionConfig/GetCommissionById",
  DOWNLOADRECORD: "/api/CommissionMgmt/DownloadCommissionExcel",
  GEOHIERARCHY: "/api/Agent/GeoHierarchy",
  GEOHIERARCHYTABLE: "/api/Agent/GeoChildren",
  HMSDASHBOARD: "/api/HMSDashboard/GetHMSDashboard",
  CHANNELSTATS: "/api/HMSDashboard/channel-stats",
  UPLOADFILELIST: "/uploaded-file-list",
  DOWNLOADREPORT: "/download-report",
  GETMASTERS: "/api/AppMasters/get",
  UPLOADFILES: "/api/file",
  GETROLES: "/api/Access/Role/List",
  DELETEROLES: "/api/Access/Role/Delete",
  FETCHMENU: "/api/Access/Role/MenuAccess",
  USERLIST:"/api/Access/Role/UserList",
  GRANTMENU:"/api/Access/Role/MenuAccess/Grant",
  REVOKEMENU:"/api/Access/Role/MenuAccess/Revoke",
  REMOVEUSER:"/api/Access/Role/RemoveUser",
  CREATEROLE:"/api/Access/Role/Create",
  ADDUSER:"/api/Access/Role/AddUser",
  GETHIERARCHY:"/api/Access/Role/UI/Control/AccessList",
  FIELDUPDATE:"/api/Access/Role/UI/Control/UpdateAccess",
  CHANNELLIST:"api/AppMasters/Channel/Fetch",
  SUBCHANNELLIST:"api/AppMasters",
  FETCHINBOX:"/api/UserInbox/FetchSr",
  UPDATESRDECISION:"/api/UserInbox/UpdateSrDecision",
  CREATECHANNEL:"api/AppMasters/Channel/Create",
  CREATESUBCHANNEL:"api/AppMasters",
  GETUSERIDS: "/api/Users/GetUserIds",
  GETUSERDETAILS:"/api/Users/GetUserDetails",
  CREATEUSER:"/api/Users/CreateUser",
  UPDATEUSER:"/api/Users/UpdateUser",
  UPDATEPASSWORD:"/api/Users/UpdatePassword",
  ACTIVEDEACTIVEUSER:"/api/Users/ActivateDeactivateUser",
  LOCKUNLOCKUSER:"/api/Users/LockUnlockUser",
  ORGCONFIG:"/api/Access/ApprovalSettings/Fetch",
  ORGCONFIGUPDATE:"/api/Access/ApprovalSettings/Save",
  REFRESHTOKEN: "/api/Auth/refreshtoken",
  AGENTSEARCHFORPARTNER: "/api/Agent",
  // Graph (external service)
  GETGRAPHDATA: "http://hmsapi.ezytekapis.com/GetGraphData",
  // Incentive (external HMS API) — matches Postman: /api/incentive/UpsertWeightage
  INCENTIVE_UPSERT_WEIGHTAGE:
    "http://hmsapi.ezytekapis.com/api/incentive/UpsertWeightage",
  FETCHALLBRANCHES: "/api/AppMasters/GetRegulatorBranches",
  SAVEAGENTLINKEDBRANCH: "/api/Agent/RegulatorBranch/Save",
  FETCHBRANCHBYAGENT: "/api/Agent/RegulatorBranch/FetchByAgent",
  CREATEINDIVIDUALAGENT: "/api/Agent/CreateIndividualAgent",
  SAVEUSERLINKEDBRANCH: "/api/Users/RegulatorUserBranch/Save",
  FETCHBRANCHBYUSER: "/api/Users/RegulatorUserBranch/FetchByUser",
  // Fallback routes (some environments expose these paths instead)
  SAVEUSERLINKEDBRANCH_V2: "/api/Users/RegulatorBranch/Save",
  FETCHBRANCHBYUSER_V2: "/api/Users/RegulatorBranch/FetchByUser",
  SAVEPRODUCT: "/api/AppMasters/SaveProduct",
  GETPRODUCTS: "/api/AppMasters/GetProducts",
  INCENTIVE_UPSERT_PROGRAM: "/api/incentive/UpsertProgram",
  INCENTIVE_GET_KPIS_LIST: "/api/incentive/GetKpisList",
  INCENTIVE_GET_SELECTED_PROGRAM_KPIS: "/api/incentive/GetSelectedProgramKpis",
  INCENTIVE_UPSERT_PROGRAM_WEIGHTAGES: "/api/incentive/UpsertProgramWeightages",
  INCENTIVE_GET_PROGRAMS_LIST: "/api/incentive/GetProgramsList",
  // Single program details by id (used for edit flow)
  INCENTIVE_GET_PROGRAM_DETAILS: "/api/incentive/GetProgramDetails",
  INCENTIVE_GET_AGENT_CLUBS: "/api/incentive/GetAgentClubs",
  INCENTIVE_GET_PROGRAM_CLUBS: "/api/incentive/GetProgramClubs",
  INCENTIVE_UPSERT_PROGRAM_CLUBS: "/api/incentive/UpsertProgramClubs",
  GET_FILTERS_CASCADE: "/api/incentive/filters/cascade",
  UPSERT_PROGRAM_FILTERS: "/api/incentive/UpsertProgramFilters",
  INCENTIVE_GET_KPI_OBJECTS: "http://hmsapi.ezytekapis.com/api/incentive/GetKpiObjects",
  INCENTIVE_GET_KPI_FIELDS: "http://hmsapi.ezytekapis.com/api/incentive/GetKpiFields",
  INCENTIVE_GET_TABLE_SCHEMA: "http://hmsapi.ezytekapis.com/api/incentive/GetTableSchema",
  INCENTIVE_GET_KPI_DETAILS: "http://hmsapi.ezytekapis.com/api/incentive/GetKpiDetails",
  INCENTIVE_UPSERT_KPI: "http://hmsapi.ezytekapis.com/api/incentive/UpsertKpi",

};

module.exports = { APIRoutes };
